# Generated by Django 5.0.1 on 2024-04-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('registration_num', models.CharField(max_length=20)),
            ],
        ),
    ]
