# Generated by Django 5.0.1 on 2024-03-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
