# Generated by Django 5.0.1 on 2024-03-30 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_email_profile_mobile_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
