# Generated by Django 5.0.1 on 2024-03-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_products_sellermobilenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
